### ISSUE TITLE
[Q&A] Production system - estimated availability

### ISSUE THREAD

**Issue by sebastian-walz** [nav-gov-hu/Online-Invoice#147]
Since we have already some customers who are ready for version 2.0, do you already have a go-live date for the 2.0 production environment?

At the official site, I found the following statement:

> The 2.0 invoice reporting interface only works in a test environment in 2019, the earliest deployment in the production environment is expected by February 2020. We will publish the exact date of this.

**Comment by NTCA-developer** [comment]
Hi @sebastian-walz ,

Thank you for your question. We estimate the deployment of the full 2.0 XML API functionality is going to be done on the next week in the production environment. The exact date and time is still under discussion because the deploy will require a substantial downtime.

The website will be updated as soon as the official timeframe is set, but I'll be happy to post it under your ticket at the time of the publication as well. I'll leave the ticket open until then.

**Comment by NTCA-developer** [comment]
Hi @sebastian-walz ,

Currently we plan to scale down the production environment on 27.02 from 18 hrs, and we estimate the downtime will last for 5 hours. After scaling up the application again the 2.0 XML API is going to be operational.
