### ISSUE TITLE
Communication error

### ISSUE THREAD

**Issue by lazaralexandra** [nav-gov-hu/Online-Invoice#255]
Error sending HTTP request to Error sending HTTP request to https://api.onlineszamla.nav.gov.hu:443/invoiceService/v2/manageInvoice. (org.mule.api.MessagingException)
June 16th 2020, 15:25 IST
Could You please check what error You get at their end?

Besides do You have any detailed explanation what this error message means as it seems userID, keys and pswd are correct. We have tried to implement solution for new technical user.
invalid_client;wrong   client_id or client_secret(401)

Company: FLEXTRONICS ODM LUXEMBOURG S.A.
VAT ID: HU30359730

**Comment by NTCA-supporter** [comment]
Dear @lazaralexandra !
Please use the test environment first, because we can check the logs and database only on test env.
If it's not possible for you for some reason, you can contact NAV officially, but I think it's easier to try the same things on test env.
Anyway the response code is 401 only in case of wrong technical user credentials (including the password's hash calculation), so probably the problem is something around that data.

Regards

**Comment by NTCA-supporter** [comment]
Hi @lazaralexandra !
Could you solve the problem? Do you have any more questions?
Thanks

**Comment by NTCA-developer** [comment]
I'm closing the ticket due to inactivity. Please reopen it or create a new one if need arises.
