### ISSUE TITLE
[FEATURE] Test Landscape/system would be very helpful to have

### ISSUE THREAD

**Issue by Andreas-Killinger** [nav-gov-hu/Online-Invoice#29]
Hello, 
i am Product Manager for eInvoicing, eTax and PEPPOL at SEEBURGER. 
SEEBURGER is worldwide locted and Provider for Solutions like NAV to our customer. What i am missing and would be very helpful is a test system similar like FatturaPA Italy (SDI) or MTDfB / HMRC in UK. What means we can send any  "test Invoices" to this testsystem and would get a Response from NAV as well before we implement our solution to all our customer straight in a productive landscape. 
Is there a plan in the nearest future to get a test System?

Thanks
Best Regards 

Andreas Killinger

**Comment by NTCA-developer** [comment]
Hello @Andreas-Killinger,

The public test system has been estabilished way before (approx 6 months before) than the production system. You can visit it here: https://onlineszamla-test.nav.gov.hu/

Please refer to the API addresses in the API documentation under section 6.1.

**Comment by Andreas-Killinger** [comment]
Hello 
sure but for this i need the log on data from our customers. 
We would like to test e.g.  with "test user data".
Is this possible?

Thanks
Regards 
Andreas Killinger

**Comment by NTCA-developer** [comment]
Hi,

Oh I see. You would like some dummy taxpayer which you could use without valid registration. The problem is theoretical, because we need to guarantee that the test system is identical with the production system. Hence, we can not allow some dummy entity to bypass proper authentication and authorization - which would be the core of your suggestion - on the test system, because it would be unacceptable on the production system. (plus, it would violate the identical functioning rule, because there would be errors that would be untriggerable by the dummy entity, like the NOT_REGISTERED_CUSTOMER error and such)

One way of implementing a function like this in general is to set up an application parameter which can control the behaviour such asymmetrical functions between environments. But I have a hard time seeing this accepted by the decision makers, hence a parameter like this is - simply put - a major security risk.

Many foreign development agencies flanked this problem by asking one of their hungarian clients to do the registration and lend them a technical user capable of calling the API. Could this be a temporary fix for your current situation?

Nevertheless, I understand your point of view and I can see the validity of what you are suggesting. Give me a short break, let's see what I can come up with.

**Comment by kabelnet2** [comment]
"approx 6 months before"
This means that the V2 test system will be available from start of July? 
There will be two (both V1 and V2) or only one (V2) test system in this period (07-12)?

**Comment by KimmerGy** [comment]
Csatlakozva kabelnet2 kérdéséhez:
lesz párhuzamos számlabefogadás az éles verzióban az  1.1 XSD és a 2.0 XSD -val  (például) 1 hónapon keresztül ? Mint volt az 1.0 XSD ről az 1.1 XSD -re  átállás esetében ?

**Comment by Andreas-Killinger** [comment]
> Hi,
> Oh I see. You would like some dummy taxpayer which you could use without valid registration. The problem is theoretical, because we need to guarantee that the test system is identical with the production system. Hence, we can not allow some dummy entity to bypass proper authentication and authorization - which would be the core of your suggestion - on the test system, because it would be unacceptable on the production system. (plus, it would violate the identical functioning rule, because there would be errors that would be untriggerable by the dummy entity, like the NOT_REGISTERED_CUSTOMER error and such)
> One way of implementing a function like this in general is to set up an application parameter which can control the behaviour such asymmetrical functions between environments. But I have a hard time seeing this accepted by the decision makers, hence a parameter like this is - simply put - a major security risk.
> Many foreign development agencies flanked this problem by asking one of their hungarian clients to do the registration in the test environment and lend them a technical user capable of calling the API. Could this be a temporary fix for your current situation?
> Nevertheless, I understand your point of view and I can see the validity of what you are suggesting. Give me a short break, let's see what I can come up with.

Hi,
thanks for your Feedback. Sure i will wait.
Thanks

**Comment by NTCA-developer** [comment]
Hy all!

Sorry for disappearing. I will reply for each of you. 
 
@kabelnet2 

> "approx 6 months before"
> This means that the V2 test system will be available from start of July?
> There will be two (both V1 and V2) or only one (V2) test system in this period (07-12)?

No, by that I solely meant that the public test had been estabilished on January of 2018. In other words, approx 6 months before the production system, which went live on July of 2018. See the project board for the implementation status of 2.0.

@KimmerGy 

Természetesen lesz párhuzamosság a két verzió között. Lesz majd egzaktabb kommunikáció az ütemezésekről, de azt szeretnénk, hogy a 2.0 szeptember végéig teljes pompájában elkészüljön és elérhető legyen a teszt környezetben. Mivel ez nagy átállás, szeretnénk a kliens oldali fejlesztések idejére code freeze-t a mi oldalunkon, amit sajnos az 1.0 alatt nem tudtunk nektek biztosítani.

@Andreas-Killinger 

I escalated your suggestion to the highest level. Still waiting for reply, stay in touch.

**Comment by NTCA-developer** [comment]
Hi @Andreas-Killinger ,

Thank you for your patience. Despite your requirement makes point for foreign developers I am sorry to say that request has been turned down. NTCA is hesitant to support a different behaviour in the test environment than it is in production, ehich is also a valid point of view. (the problem space we discussed earlier)

In light of the decision I'm closing the ticket. Thank you for your understanding and the effort you took to highlight the problem.
