### ISSUE TITLE
 upload XML file in NTCA

### ISSUE THREAD

**Issue by vkozakevich** [nav-gov-hu/Online-Invoice#700]
We have problem with validation upload file in NTCA. We have element intermediatedService  with value "true". And NTCA excited one of fields (see attachments).
Which field and value should we fill in file, if intermediatedService ='true'?
Problémánk van az NAV feltöltési fájljának érvényesítésvel. Ennek az elemnek „intermediatedService” az értéke „true”. És a NAV visszajelzése alapján nem fogadta el az egyik mezőt (lásd a mellékletet).
Melyik mezőt és értéket kell kitölteni a fájlban, ha az intermediatedService = 'true' értéket szeretném felvinni? Köszönöm előzetesen is válaszukat.
![error](https://user-images.githubusercontent.com/77329708/104308072-229cac80-54e1-11eb-8454-0c6d1ca4c8f8.jpg)

**Comment by renced42** [comment]
Dear @vkozakevich 
As I see the error message, there is no problem with the intermediatedService value.
The problem is that you got a wrong element order or wrong element in the XML structure.

**Comment by vkozakevich** [comment]
I added upload file.  Can you explain to me where I have an error in the file structure. If remove the intermediatedService  element, then the file is loaded without errors.
[upload.zip](https://github.com/nav-gov-hu/Online-Invoice/files/5808557/upload.zip)

**Comment by renced42** [comment]
Dear @vkozakevich 

The problem is the place of the intermediatedService tag.
If you see the 2.0 xsd the intermediatedService tag is come after the lineAmountsNormal or lineAmountsSimplified choice member. In the uploaded xml the  intermediatedService tag is precede the lineAmountsNormal tag. So that is why you get an XSD validation error. You should correct the tags order and the validation will be ok.
