### ISSUE TITLE
Invalid_Request_Signature Error received while submitting the ManageInvoice [DEV support]

### ISSUE THREAD

**Issue by AmrutaK1** [nav-gov-hu/Online-Invoice#827]
> **Használati feltételek / Use conditions:**
Fejlesztői támogatás csak és kizárólag a teszt környezetben az XML API implementációjának támogatására vehető igénybe. Bármely a tárgynak nem megfelelő, éles üzleti/authentikációs adatot vagy forráskódot tartalmazó ticketet törölni fogunk. A gyors válaszadás érdekében kérjük hogy minden félkövérrel kiemelt adat legyen megadva! / It is only possible to request DEV support for the implementation of the XML API and only on the test environment. Each ticket that has a different subject, contains production business/authentication data or source code is going to be deleted. To provide prompt response please fil out all necessary info marked with bold.

**Környezet / Environment**
**[x] https://api-test.onlineszamla.nav.gov.hu**

**Hívott API operáció / called API operation**

**[] /manageInvoice**

**A kérés verziója / version of the request**
**[] 3.0**

**A requestId értéke / requestId value**
```

```

**A probléma rövid és tömör leírása / Clear and concise description of the problem**

**Receiving the Invalid Request Signature error inspite of correctly configuring the algorihm**

*Egyéb tartalom / Additional content*
###

**Comment by csandazoltan** [comment]
You should elaborate on that for get help sooner...

Do you have an xsd error? Because compared to v2, the method of calculation didn't changed, but the structure of signature did changed

Copy in the relevant part of the xml request, or give the requestId.... support gonna ask for those,

**Comment by AmrutaK1** [comment]
Hi Team,

Below is the header and user tag from the request XML


**<header>
        <requestId>E877CA51140A440CA1D257D83</requestId>
        <timestamp>2021-03-19T18:36:04.000Z</timestamp>
        <requestVersion>3.0</requestVersion>
        <headerVersion>1.0</headerVersion>
    </header>
    <user>
        <login>j9wzm0hx64po212</login>
        <passwordHash cryptoType="SHA-512">518B6F040DFD58504E632CC3BF597A8B2DC16231EAF92084DF7F6E5B043C9C9BFEE3CEBD51A2BC5D5B116D116D5CF1C7BC3EEB725C1F39078692955E800B2A41</passwordHash>
        <taxNumber>10518869</taxNumber>
        <requestSignature cryptoType="SHA3-512">5362D2F09FD340D8761607666C8B26E4215C7CBA2E0DE9DCB567CF9B9BFB1B64BE320FB7586D445C50A130AF481D0E440DF780787B1116FA86E520C77F783A3D</requestSignature>
    </user>**

**Comment by AmrutaK1** [comment]
<header>
        <requestId>E877CA51140A440CA1D257D83</requestId>
        <timestamp>2021-03-19T18:36:04.000Z</timestamp>
        <requestVersion>3.0</requestVersion>
        <headerVersion>1.0</headerVersion>
    </header>
    <user>
        <login>j9wzm0hx64po212</login>
        <passwordHash cryptoType="SHA-512">518B6F040DFD58504E632CC3BF597A8B2DC16231EAF92084DF7F6E5B043C9C9BFEE3CEBD51A2BC5D5B116D116D5CF1C7BC3EEB725C1F39078692955E800B2A41</passwordHash>
        <taxNumber>10518869</taxNumber>
        <requestSignature cryptoType="SHA3-512">5362D2F09FD340D8761607666C8B26E4215C7CBA2E0DE9DCB567CF9B9BFB1B64BE320FB7586D445C50A130AF481D0E440DF780787B1116FA86E520C77F783A3D</requestSignature>
    </user>

**Comment by csandazoltan** [comment]
Use that to put code into response
![image](https://user-images.githubusercontent.com/6756505/112477737-9a097a80-8d73-11eb-8bc9-7ae1e70b4a23.png)

`<xml>your xml will look like a code<code>`

**Comment by AmrutaK1** [comment]
`<header>
        <requestId>E877CA51140A440CA1D257D83</requestId>
        <timestamp>2021-03-19T18:36:04.000Z</timestamp>
        <requestVersion>3.0</requestVersion>
        <headerVersion>1.0</headerVersion>
    </header>
    <user>
        <login>j9wzm0hx64po212</login>
        <passwordHash cryptoType="SHA-512">518B6F040DFD58504E632CC3BF597A8B2DC16231EAF92084DF7F6E5B043C9C9BFEE3CEBD51A2BC5D5B116D116D5CF1C7BC3EEB725C1F39078692955E800B2A41</passwordHash>
        <taxNumber>10518869</taxNumber>
        <requestSignature cryptoType="SHA3-512">5362D2F09FD340D8761607666C8B26E4215C7CBA2E0DE9DCB567CF9B9BFB1B64BE320FB7586D445C50A130AF481D0E440DF780787B1116FA86E520C77F783A3D</requestSignature>
    </user>`

**Comment by AmrutaK1** [comment]
Above is the chunk of code from the request

**Comment by NTCA-supporter** [comment]
Hi @AmrutaK1 !
I copy here the log entry:
Invalid request signature, actual:[5362D2F09FD340D8761607666C8B26E4215C7CBA2E0DE9DCB567CF9B9BFB1B64BE320FB7586D445C50A130AF481D0E440DF780787B1116FA86E520C77F783A3D], expected:[55E2516F97C2B0703C8F0DBD181E31EDF4C427D0B2A942D37B49C6AD4989EA4B031B970900D0DDA8AFEE7369A2DF1DBF0F67F0E172182B8C868A1C03C0724BB7]

You can check the result with your values. This function works well for everybody, so the calculation issue must be on client side.
Br

**Comment by AmrutaK1** [comment]
This is the same calculation we used for V2.0 which worked well! But not sure what is going wrong with V3.0?
Also will the content of InvoiceData matter for creation of request signature?

**Comment by AmrutaK1** [comment]
Also one thing to note I am getting a valid response after hitting the token exchange webservice.
And I am using the same method to populate the request signature tag for generating the Token Exchange Request

Thanks.

**Comment by NTCA-supporter** [comment]
Hi @AmrutaK1 !
Please check again the documentation: https://onlineszamla.nav.gov.hu/api/files/container/download/Online%20Szamla_Interfesz%20specifikacio_EN_v3.0.pdf
Chapter 1.5

The method is the same as it was in version 2.0. And yes, the base64 encoded value of the invoiceData xml should be also part of the calculation.
Br

**Comment by NTCA-supporter** [comment]
Hi @AmrutaK1 !
Could you resolve the issue?
Br

**Comment by kabelnet2** [comment]
Igen lezárhatod, megoldották a problémát. Bár kértem, hogy zárja le, úgy tűnik azt már nem találta fontosnak.
Köszönöm a segítséget a nevükben (Infosys) is!

**Comment by v-sesima** [comment]
@AmrutaK1 , @kabelnet2
Could you please share any details that helped to solve the issue? We are facing a similar random error and cannot determine the reason. Any help would be essential.

**Comment by v-sesima** [comment]
Hello @renced42 

I have doubts actually because we haven't changed the code since V2.0 in a part of requestSignature calculation. I will describe the issue more fully.

We face the INVALID_REQUEST_SIGNATURE error when having several invoices included in manageInvoiceRequest. By the way, tokenRequest is sent successfully. However, sending the entire invoices separately one by one does not produce any error and all of them can be accepted by the system. As I have mentioned the error is rare and random.

**Comment by renced42** [comment]
Yes it is clear but trust me this function is not making error at server side.
The only way is to logging the full procedure and check manually the calculated hash.
At that point we will se the truth.

**Comment by csandazoltan** [comment]
@v-sesima Since you can submit single invoices, i assume your xml is valid and passes the xsd check and the preblem is in the data.

You said request signature is also ok, when sending multiple invoices things start to break down.
In all cases or sometimes?
Because i had a similar problem and my problem was with the hashes.
It is hard to diagnose without looking at the unhashed string

When you do a request token, you hash 
hash(`request id+timestamp+user signature key`)

When you send a single invoice, you hash 
`hash(request id+timestamp+user signature key+hash(INVOICE OPERATION+BASE64))`

When you send a multiple invoices, you nest the hashes, you hash a string containing multiple hashes
`hash(request id+timestamp+user signature key+hash(INVOICE OPERATION+BASE64)+hash(INVOICE OPERATION+BASE64)+hash(INVOICE OPERATION+BASE64))`

While the request signature method didn't change, I would take a gander at how you stich your hashes together before you make a big hash, even going back to BASE64 generation, whether you do any trimming or string manipulation, because my issue was that i had whitespaces in the unhashed string and it made a difference in the big hash

Look at the unhashed big string when you submit multiple invoices and check all your separate hashes individually

I am curious about where it goes wrong.

**Comment by v-sesima** [comment]
Hi everybody. Just want to leave here the info on my issue for the history purposes. I wish it useful for someone.

In our case, we had an error on the application side. @renced42 , you were right to be so confident.

The error appeared from time to time due to difference in invoices ordering in ManageInvoiceRequest and when taking them for requestSignature calculation. According to official documentation: _The calculated hash values should be appended after the partial hash, in the order corresponding to the indices._ It is about the second part of the string which has concatenation of invoices hashes:
`hash(INVOICE OPERATION+BASE64)+hash(INVOICE OPERATION+BASE64)+hash(INVOICE OPERATION+BASE64)`

We used ordering when enumerating and listing invoices in the ManageInvoiceRequest and did not use ordering when concatenating these hashes. After adjusting the invoices ordering in both cases the issue was resolved.

Thanks for advices and help.
