### ISSUE TITLE
Test NAV

### ISSUE THREAD

**Issue by vkozakevich** [nav-gov-hu/Online-Invoice#878]
Hello.
Test NAV is not working. And we can't test xml file. When test system will be work?

**Comment by NTCA-supporter** [comment]
Hi @vkozakevich !

In the Online Invoice system, we will soon introduce the KAÜ identification, which will be tested on the Online Invoice system test portal before the implementation. Therefore, access to the test interface will be temporarily suspended from 17:00 on 30 April. This will not affect the m2m interface, which will continue to be used.

Due to the suspension, technical annulments initiated on the m2m interface cannot be approved and authorisations cannot be granted or withdrawn, and it is not possible to register on the test system.

We thank our users for their patience!

Br

**Comment by ballonyi** [comment]
Kérdezni szeretném hogy mikor lesz újra elérhető a tesztkörnyezet?

**Comment by abdallahbeshi** [comment]
@NTCA-supporter Since the test environment website is temporarily down, how is it possible to modify the privileges of a technical user? apparently there is something wrong with the privileges because I get:
```
                <ns2:validationErrorCode>CUSTOMER_NOT_ASSIGNED</ns2:validationErrorCode>
                <ns2:message>Not authorized customer tax number.</ns2:message>
```

for all the requests i make, but since the website is down, there is no way to change the privileges or add a new account..etc

Thanks

**Comment by vilagosiarpad** [comment]
Tisztelt @NTCA-supporter!
Én is érdeklődnék, hogy mikor lesz végre elérhető a teszt, mert szeretnénk tesztelni, amihez regisztrálnunk is kellene?
Előre is köszönöm a választ!

**Comment by NTCA-supporter** [comment]
Hi All!

It's available now. Thank's for the patience!
Br

Sziasztok!

Újra elérhető, köszönjük a türelmet.
Üdv
