### ISSUE TITLE
[Q&A] Inbound process

### ISSUE THREAD

**Issue by Antonikas58** [nav-gov-hu/Online-Invoice#997]
Hi team,
I have a question about the usage of the webservice in case of incoming files. If our company for example receive some inbound invoices  which methods of the service we need to use to get all the incoming documents if we do not know the invoice number itself?

Best regards
Anton

**Comment by csandazoltan** [comment]
As far as I know, NAV doesn't store documents.
The interface specification in english, section 2.6 "Electronic invoicing support"

In short: 
Either the generated medium, whether it be PDF, JPG or TXT, is hashed by the currently accepted hashing algorythm and just the hash is sent to NAV the document itself has to be stored by the seller and the buyer, how the document itself gets there is up to the agreement between parties. It is their responsibility
During an audit that hash is used to authenticate the digital documents

or the other form is when the parties agree to exchange the invoice totally electronically trought the webservice without any extra files, starting from the 3.0 version, meaning the submission to NAV itself, the xml data becomes the electronic invoice, which is again the responsibility of the parties to store

---

Your question cannot be answered here since what you are looking for is not the responsibility of NAV. 
You can get your INBOUND invoicenumbers trough the /queryInvoiceDigest api and get the format and HASH of the invoice with the /queryInvoiceData api. 

The webservice will only provide you with the electronic invoice, if that invoice is submitted as a electronic invoice with the completenessIndicator equal to true, then the xml in invoicedata is the invoice document.

For any other format, like PDF. Putting aside that you should already have that, you need to contact every issuer individually and request a copy of the invoice files submitted to NAV and store them appropriately. 
(and check the hashes to be sure they sent the same document)

**Comment by Antonikas58** [comment]
Hi Zoltan,
Thanks a lot for your reply, i have one more question related mostly to /queryInvoiceDigest method. When we initially get the list of inbound documents using Invoice Digest and later on we receive Invoice Data itself we save it in our datastore and process further. The question is if there is a way of how to mark the document that we already processed, so that using the method /queryInvoiceDigest we will already know that we have this document already and do not even need to check that?

**Comment by csandazoltan** [comment]
You can't do that, the webservice doesn't have it, it only provides data based on your search parameters.
You need to keep track of your processing and mark in your system whether something is processed or not

If you look at a day, you are going to get the data of that day.

You talking again about "documents" NAV doesn't give you document, except when completeness indicator is true.
I'm not a invoice law expert, but as far as i know, IF there is a dociment, whether it is paper or PDF or JPG or TXT, somewhere about an invocie and NAV only has the hash of it. You are obligated to get that document by any means and store it for x amount of year, in case of a NAV audit.

Storing the queryInvoiceDigest and  queryInvoiceData is not always enough, that is not in compliance with current laws....
But we are communicating in english, I do not know where you are at now and whether hungarian tax law applies to you or not the same way....
I cannot help you with that

**Comment by NTCA-supporter** [comment]
Hi!
I close this issue. If you have any firther question, feel free to reopen it.
Br
